### ISSUE TITLE
Weather only sync when i open app

### ISSUE THREAD

**Issue by tpoddar** [ls6777/FitbitWatchAnalogClock#3]
The weather only updates when i open the Fitbit app. Otherwise it just stays same

**Comment by ls6777** [comment]
Are you on Versa or Versa 2?

What happens when you hit the left button?

What location are you in?

**Comment by tpoddar** [comment]
Im in london. When i hit the left button it just turns off and on the screen

**Comment by tpoddar** [comment]
Versa2

**Comment by ls6777** [comment]
ok... the fit bit will only update about once per hour.  This is to save battery on the fitbit.  To get the weather, the fitbit must communicate with the phone, which will run down the battery faster if done too often.  

If you check it and wait an hour or 2, are you still seeing it not update unless you open the fitbit app?

Also, for it to update, the fitbit app must be allowed to run in the background on the phone, otherwise the watch can not get the latest updates for the weather.

**Comment by tpoddar** [comment]
Hi
The Fitbit app is allowed to run in background.

**Comment by ls6777** [comment]
What about my other question.  Have you checked it like 2 hours later to see what it says?

**Comment by tpoddar** [comment]
Let me wait and see what happens. I have also enabled the location so that
it always has location access and not just when using app

**Comment by tpoddar** [comment]
Like like i had to enable locationb all the time and not just when using
app to enable the app to pick up location and display the weather

**Comment by ls6777** [comment]
I see... that makes sense because it needs your location to get the weather updates.
so is it working properly now?

**Comment by tpoddar** [comment]
Yes

**Comment by ls6777** [comment]
Thanks! This will be useful info for future users who run into a similar issue 👍
