### ISSUE TITLE
Changing F to C in the Weather

### ISSUE THREAD

**Issue by timday01** [ls6777/FitbitWatchAnalogClock#5]
Hello. Digging the clock face, however, even though my FitBit is set to C for temperature, the clock face still shows F.  How can I change this?

Thanks!

**Comment by ls6777** [comment]
ok... I know this is going to be annoying, but Versa and Versa 2 don't have the same settings for units that the newer watches have.  The units are all linked to the Length Units.  I don't know why they did it this way, but I can't change it for the Versa or Versa 2 because they don't support the latest versions of the SDK that Versa 3 does. So....

If you want C for temp, then you need to: 

1. go to Account -> App Settings -> Units  in the Fitbit app. 
2. Change length from feet/miles to Centimeters/Kilometers
3. Then go to you device and do a sync now.
4. After the sync is successful, you should see the elevation change from feet to meters
5. Then just tap the face of the watch, you should see the temp go to '--', and then when it gets the updated weather, it should be displayed in C

Obviously, the problem is that elevation, and possible other stats that rely on length unit, will be displayed in metric.

Again... this is a fitbit limitation in SDK for versa and versa 2 that I have no control over.  The temperature unit in the app setting has no effect on what the temp is displayed in for my watch face.

Let me know if you continue to have issues, but I just tested this on my Versa 2 and it works as described above.

**Comment by timday01** [comment]
Ha.  Seems weird length is tied to temp. It worked. Thanks!


Sent from Yahoo Mail for iPhone


On Sunday, July 31, 2022, 11:36 PM, ls6777 ***@***.***> wrote:




ok... I know this is going to be annoying, but Versa and Versa 2 don't have the same settings for units that the newer watches have. The units are all linked to the Length Units. I don't know why they did it this way, but I can't change it for the Versa or Versa 2 because they don't support the latest versions of the SDK that Versa 3 does. So....

If you want C for temp, then you need to:
   
   - go to Account -> App Settings -> Units in the Fitbit app.
   - Change length from feet/miles to Centimeters/Kilometers
   - Then go to you device and do a sync now.
   - After the sync is successful, you should see the elevation change from feet to meters
   - Then just tap the face of the watch, you should see the temp go to '--', and then when it gets the updated weather, it should be displayed in C

Obviously, the problem is that elevation, and possible other stats that rely on length unit, will be displayed in metric.

Again... this is a fitbit limitation in SDK for versa and versa 2 that I have no control over. The temperature unit in the app setting has no effect on what the temp is displayed in for my watch face.

Let me know if you continue to have issues, but I just tested this on my Versa 2 and it works as described above.
